# -*- coding: utf-8 -*-
"""Structured Cognitive Intelligence Loop for FRIDAY Agent.

Architecture:
UNDERSTAND -> CLARIFY -> PLAN -> CHECK PLAN -> AUTHORIZE -> EXECUTE -> OBSERVE -> VERIFY -> LEARN -> COMPLETE

Core Capabilities:
- Confidence calibration across all cognitive phases (understanding, planning, perception, tool selection, verification).
- Autonomous thresholding:
  * Lacks information -> Triggers CLARIFY with targeted questions.
  * Perception required -> Engages active screen perception pipeline.
  * Memory useful -> Queries semantic and episodic memory.
  * Tool necessary -> Determines when tools are needed vs direct answering.
  * Plan unsafe -> Flags safety hazards and enforces authorizer gating.
  * Action failed -> Dispatches evidence-based bounded recovery.
  * Strict Invariant: High confidence NEVER bypasses authorization policies.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
import json
import re
from typing import Any, Callable, Dict, List, Optional, Set, Tuple
import uuid

from friday.agent.goal import Goal, GoalRequestType, GoalRiskLevel, GoalUnderstandingEngine
from friday.agent.planner import PlanStep, StepStatus, TaskPlan
from friday.agent.state import ReasoningStateMachine, TaskState
from friday.agent.verification import StepVerifier, VerificationResult, VerificationStatus
from friday.core.auth import BaseAuthorizer, DefaultSecureAuthorizer
from friday.core.logging import get_logger
from friday.core.types import AuthorizationDecision, AuthorizationRequest, Message, Role, SafetyLevel, ToolResult
from friday.llm.base import BaseLLMProvider
from friday.security.scrubber import redact_secrets

logger = get_logger("agent.cognitive")


class CognitivePhase(str, Enum):
    """Phases of the structured cognitive intelligence loop."""
    UNDERSTAND = "UNDERSTAND"
    CLARIFY = "CLARIFY"
    PLAN = "PLAN"
    CHECK_PLAN = "CHECK_PLAN"
    AUTHORIZE = "AUTHORIZE"
    EXECUTE = "EXECUTE"
    OBSERVE = "OBSERVE"
    VERIFY = "VERIFY"
    LEARN = "LEARN"
    COMPLETE = "COMPLETE"


@dataclass
class ConfidenceAssessment:
    """Calibrated confidence scores and rationale across cognitive dimensions."""
    understanding_confidence: float = 1.0
    planning_confidence: float = 1.0
    perception_confidence: float = 1.0
    tool_selection_confidence: float = 1.0
    verification_confidence: float = 1.0
    reasons: List[str] = field(default_factory=list)

    @property
    def min_confidence(self) -> float:
        return min(
            self.understanding_confidence,
            self.planning_confidence,
            self.perception_confidence,
            self.tool_selection_confidence,
            self.verification_confidence,
        )

    def is_clarification_required(self, threshold: float = 0.65) -> bool:
        """Determines if confidence is too low, requiring user clarification instead of guessing."""
        return self.understanding_confidence < threshold or self.planning_confidence < threshold

    def to_dict(self) -> Dict[str, Any]:
        return {
            "understanding_confidence": round(self.understanding_confidence, 2),
            "planning_confidence": round(self.planning_confidence, 2),
            "perception_confidence": round(self.perception_confidence, 2),
            "tool_selection_confidence": round(self.tool_selection_confidence, 2),
            "verification_confidence": round(self.verification_confidence, 2),
            "min_confidence": round(self.min_confidence, 2),
            "reasons": self.reasons,
        }


@dataclass
class CognitiveDecision:
    """Decision output generated by the cognitive intelligence loop."""
    current_phase: CognitivePhase
    confidence: ConfidenceAssessment
    lacks_information: bool = False
    clarification_prompt: Optional[str] = None
    perception_required: bool = False
    memory_useful: bool = False
    tool_necessary: bool = False
    plan_unsafe: bool = False
    requires_user_confirmation: bool = False
    should_continue_autonomously: bool = True
    suggested_action: Optional[str] = None
    explanation: Optional[str] = None


class CognitiveIntelligenceEngine:
    """Orchestrates structured cognitive evaluation and confidence tracking."""

    # Keywords signaling visual perception need
    PERCEPTION_KEYWORDS = {
        "screen", "see", "look", "button", "window", "click", "app",
        "cursor", "icon", "dialog", "display", "ui", "visible", "screenshot"
    }

    # Keywords signaling memory utility
    MEMORY_KEYWORDS = {
        "remember", "recall", "earlier", "previous", "yesterday", "last time",
        "before", "history", "preference", "context", "mentioned"
    }

    # Ambiguity indicator patterns
    AMBIGUOUS_PATTERNS = [
        r"^(it|that|this|do it|fix it|run)$",
        r"^(something|anything|whatever)$",
        r"^delete\s*$",
        r"^open\s*$",
    ]

    def __init__(
        self,
        llm_provider: Optional[BaseLLMProvider] = None,
        authorizer: Optional[BaseAuthorizer] = None,
        clarification_threshold: float = 0.65,
    ) -> None:
        self.llm = llm_provider
        self.authorizer = authorizer or DefaultSecureAuthorizer()
        self.clarification_threshold = clarification_threshold
        self.goal_engine = GoalUnderstandingEngine(llm_provider=llm_provider)

    def evaluate_request(
        self,
        user_input: str,
        available_tools: Optional[List[str]] = None,
        has_memory: bool = True,
        has_screen_capture: bool = True,
    ) -> CognitiveDecision:
        """Execute the UNDERSTAND & CLARIFY assessment of a user request."""
        clean_input = user_input.strip()
        words = set(re.findall(r"\b\w+\b", clean_input.lower()))

        confidence = ConfidenceAssessment()
        reasons = []

        # 1. Check for under-specified / ambiguous input
        lacks_info = False
        clarification_prompt = None

        if len(clean_input) < 3 or any(re.match(p, clean_input.lower()) for p in self.AMBIGUOUS_PATTERNS):
            lacks_info = True
            confidence.understanding_confidence = 0.3
            reasons.append("Request is highly underspecified or missing target subject.")
            clarification_prompt = f"Could you clarify what specific action or target you would like me to work on regarding '{clean_input}'?"

        # 2. Check if perception is required
        perception_required = bool(words.intersection(self.PERCEPTION_KEYWORDS)) and has_screen_capture
        if perception_required:
            reasons.append("Visual screen inspection required to resolve target UI context.")
            confidence.perception_confidence = 0.9

        # 3. Check if memory is useful
        memory_useful = bool(words.intersection(self.MEMORY_KEYWORDS)) and has_memory
        if memory_useful:
            reasons.append("Prior conversational/task memory relevant to request context.")

        # 4. Check if a tool is necessary
        tool_necessary = False
        tool_names = available_tools or []
        for t in tool_names:
            t_clean = t.replace("_", " ").lower()
            if any(part in clean_input.lower() for part in t_clean.split() if len(part) > 3):
                tool_necessary = True
                break

        if any(w in clean_input.lower() for w in ["calculate", "run", "search", "write", "read", "open", "check", "system", "file", "time", "date"]):
            tool_necessary = True

        # Compute goal understanding via GoalEngine
        try:
            goal_obj = self.goal_engine.normalize_and_decompose(clean_input)
            if goal_obj.request_type == GoalRequestType.AMBIGUOUS_REQUEST:
                lacks_info = True
                confidence.understanding_confidence = 0.4
                clarification_prompt = goal_obj.clarification_prompt or "Could you provide more details on what you want to achieve?"
        except Exception:
            pass

        confidence.reasons = reasons

        should_autonomously_continue = not lacks_info and not (confidence.understanding_confidence < self.clarification_threshold)

        phase = CognitivePhase.CLARIFY if lacks_info else CognitivePhase.PLAN

        return CognitiveDecision(
            current_phase=phase,
            confidence=confidence,
            lacks_information=lacks_info,
            clarification_prompt=clarification_prompt,
            perception_required=perception_required,
            memory_useful=memory_useful,
            tool_necessary=tool_necessary,
            should_continue_autonomously=should_autonomously_continue,
            explanation="; ".join(reasons) if reasons else "Request clear and unambiguous.",
        )

    def check_plan_safety_and_confidence(
        self,
        plan: TaskPlan,
        authorizer: Optional[BaseAuthorizer] = None,
    ) -> CognitiveDecision:
        """Execute CHECK_PLAN phase: validate safety, cycles, authorization, and plan confidence."""
        authz = authorizer or self.authorizer
        confidence = ConfidenceAssessment()
        reasons = []

        is_unsafe = False
        requires_confirmation = False

        # 1. Dependency DAG cycle validation
        try:
            waves = plan.compute_topological_schedule()
        except Exception as err:
            confidence.planning_confidence = 0.1
            reasons.append(f"Plan validation failed with dependency error: {err}")
            return CognitiveDecision(
                current_phase=CognitivePhase.CHECK_PLAN,
                confidence=confidence,
                plan_unsafe=True,
                should_continue_autonomously=False,
                explanation=str(err),
            )

        # 2. Safety level analysis
        for step in plan.steps:
            if step.safety_level in (SafetyLevel.SENSITIVE, SafetyLevel.DANGEROUS):
                is_unsafe = True
                requires_confirmation = True
                reasons.append(f"Step '{step.step_id}' ({step.tool_name}) requires formal authorization [Safety: {step.safety_level.value}].")

        # 3. Parameter validation
        for step in plan.steps:
            if step.tool_name and step.parameters is None:
                confidence.tool_selection_confidence = 0.4
                reasons.append(f"Step '{step.step_id}' has missing parameters dictionary.")

        confidence.reasons = reasons
        confidence.planning_confidence = 0.95 if not is_unsafe else 0.85

        # Critical rule: High confidence NEVER bypasses authorization
        should_continue = not is_unsafe

        return CognitiveDecision(
            current_phase=CognitivePhase.AUTHORIZE if is_unsafe else CognitivePhase.EXECUTE,
            confidence=confidence,
            plan_unsafe=is_unsafe,
            requires_user_confirmation=requires_confirmation,
            should_continue_autonomously=should_continue,
            explanation="; ".join(reasons) if reasons else "Plan verified and safe to execute autonomously.",
        )

    def evaluate_verification_and_learning(
        self,
        step: PlanStep,
        step_result: ToolResult,
        verification: VerificationResult,
    ) -> CognitiveDecision:
        """Execute OBSERVE, VERIFY, and LEARN assessment after step execution."""
        confidence = ConfidenceAssessment()
        reasons = []

        is_failure = not verification.is_real_success or verification.status != VerificationStatus.PASSED

        if is_failure:
            confidence.verification_confidence = 0.2
            reasons.append(f"Verification rejected outcome: {verification.evidence}")
            phase = CognitivePhase.OBSERVE
            should_continue = False
        else:
            confidence.verification_confidence = verification.confidence
            reasons.append(f"Evidence verified successfully: {verification.evidence}")
            phase = CognitivePhase.LEARN
            should_continue = True

        confidence.reasons = reasons

        return CognitiveDecision(
            current_phase=phase,
            confidence=confidence,
            should_continue_autonomously=should_continue,
            explanation="; ".join(reasons),
        )
