services:
  - type: web
    name: friday-friday
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "10000"
      - key: HOST
        value: "0.0.0.0"
      - key: ENVIRONMENT
        value: "production"
      - key: FRIDAY_INTELX_URL
        sync: false
      - key: FRIDAY_STRATEX_URL
        sync: false
      - key: FRIDAY_EMAIL_APP_PASSWORD
        sync: false
      - key: FRIDAY_IOT_HUB_URL
        sync: false
      - key: FRIDAY_CORTEX_API_KEY
        sync: false
      - key: FRIDAY_INFERENCE_URL
        sync: false
      - key: FRIDAY_INTELX_BASE_URL
        sync: false
      - key: FRIDAY_INTELX_API_KEY
        sync: false
      - key: FRIDAY_NEXUS_BASE_URL
        sync: false
      - key: FRIDAY_MEMORA_API_KEY
        sync: false
      - key: FRIDAY_UNIVERSE_API_URL
        sync: false
      - key: FRIDAY_FUTURIS_BASE_URL
        sync: false
      - key: FRIDAY_FORGE_API_URL
        sync: false
      - key: FRIDAY_MEMORA_URL
        sync: false
      - key: FRIDAY_FORGE_BASE_URL
        sync: false
      - key: FRIDAY_FUTURIS_API_KEY
        sync: false
      - key: FRIDAY_API_KEY
        sync: false
      - key: FRIDAY_LLM_API_KEY
        sync: false
      - key: FRIDAY_GEMINI_API_KEY
        sync: false
      - key: FRIDAY_INFERENCE_API_KEY
        sync: false
      - key: FORGE_BASE_URL
        sync: false
      - key: FRIDAY_OPENROUTER_API_KEY
        sync: false
      - key: FRIDAY_GEMINI_FALLBACK_API_KEY_2
        sync: false
      - key: FRIDAY_MEMORA_BASE_URL
        sync: false
      - key: FRIDAY_MISTRAL_API_KEY
        sync: false
      - key: FRIDAY_UNIVERSE_API_KEY
        sync: false
      - key: FRIDAY_GROQ_API_KEY
        sync: false
      - key: FRIDAY_LLM_BASE_URL
        sync: false
      - key: FRIDAY_GITHUB_TOKEN
        sync: false
      - key: FRIDAY_STRATEX_API_KEY
        sync: false
      - key: FRIDAY_FORGE_API_KEY
        sync: false
      - key: FRIDAY_IOT_HUB_TOKEN
        sync: false
      - key: FRIDAY_GEMINI_FALLBACK_API_KEY_3
        sync: false
      - key: FRIDAY_LLM_MAX_TOKENS
        sync: false
      - key: FRIDAY_FUTURIS_URL
        sync: false
      - key: FRIDAY_GEMINI_FALLBACK_API_KEY_4
        sync: false
      - key: FRIDAY_AI_UNIVERSE_BASE_URL
        sync: false
      - key: FRIDAY_CORTEX_URL
        sync: false
      - key: FRIDAY_GEMINI_FALLBACK_API_KEY_1
        sync: false
      - key: FRIDAY_TRADING_BOT_BASE_URL
        sync: false
      - key: FRIDAY_SENTINEL_BASE_URL
        sync: false
      - key: FRIDAY_CALENDAR_ICS_URL
        sync: false
