# -*- coding: utf-8 -*-
"""Evolution Oversight Operator for FRIDAY.

Supervises the trading bot's strategy evolution laboratory every 15 minutes:
- Tracks new candidates generated by genetic evolution
- Validates 6-gate compliance (Overfitting, Slippage, Regime, Max DD, Monte Carlo, Sharpe)
- Alerts when a strategy candidate is ready for human approval review
- Alerts when a strategy fails validation or when a live strategy enters probation
- Detects evolution laboratory stagnation (>3 days without candidate progression)
"""

from datetime import datetime, timezone
import threading
from typing import Any, Dict, List, Optional, Set

from friday.alert_manager import AlertSeverity, ProductionAlertManager
from friday.core.logging import get_logger
from friday.core.types import Message, Role, SafetyLevel, TrustLevel
from friday.operators.base_operator import BaseOperator, OperatorExecutionResult, OperatorState
from friday.operators.triggers import IntervalTrigger
from friday.trading.strategy_portfolio import StrategyLifecycleState, StrategyPortfolioManager

logger = get_logger("operators.evolution_oversight")


class EvolutionOversightOperator(BaseOperator):
    """High-level supervisor monitoring evolution lab progress and candidate readiness."""

    __test__ = False

    name = "evolution_oversight"
    description = (
        "Supervises the strategy evolution laboratory every 15 minutes, alerting on human approval readiness, "
        "validation failures, and live strategy probation entries."
    )

    def __init__(
        self,
        portfolio_manager: Optional[StrategyPortfolioManager] = None,
        alert_manager: Optional[ProductionAlertManager] = None,
        poll_interval_sec: float = 900.0,  # 15 minutes default
        memory: Optional[Any] = None,
        authorizer: Optional[Any] = None,
    ) -> None:
        trigger = IntervalTrigger(interval_seconds=poll_interval_sec, name="evolution_oversight_poll_interval")
        super().__init__(
            name="evolution_oversight",
            description="Supervises evolution laboratory every 15 minutes.",
            safety_level=SafetyLevel.SAFE,
            triggers=[trigger],
            notification_category="evolution_supervision",
            authorizer=authorizer,
        )
        self._portfolio_manager = portfolio_manager
        self._alert_manager = alert_manager
        self.poll_interval_sec = poll_interval_sec
        self.memory = memory
        self._alerted_candidates: Set[str] = set()

    @property
    def portfolio_manager(self) -> StrategyPortfolioManager:
        if self._portfolio_manager is None:
            self._portfolio_manager = StrategyPortfolioManager()
        return self._portfolio_manager

    @property
    def alert_manager(self) -> ProductionAlertManager:
        if self._alert_manager is None:
            self._alert_manager = ProductionAlertManager()
        return self._alert_manager

    def tick(self) -> List[Dict[str, Any]]:
        """Executes a 15-minute evolution laboratory supervisory cycle."""
        events: List[Dict[str, Any]] = []

        overview = self.portfolio_manager.get_portfolio_overview()
        candidates = overview["candidates_awaiting_review"]

        # 1. Alert on Strategy Candidate Ready for Human Approval Review
        for cand in candidates:
            c_name = cand["name"]
            if c_name not in self._alerted_candidates and cand["lifecycle_state"] == StrategyLifecycleState.READY_FOR_REVIEW.value:
                self._alerted_candidates.add(c_name)
                ev = {
                    "type": "CANDIDATE_READY_FOR_APPROVAL",
                    "candidate_name": c_name,
                    "profit_factor": cand["profit_factor_2y"],
                    "sharpe": cand["sharpe_2y"],
                    "passed_gates": cand["passed_gates_count"],
                    "message": (
                        f"Evolution lab has a new strategy candidate for review: {c_name}, "
                        f"profit factor {cand['profit_factor_2y']:.2f} over 2 years, passed all {cand['passed_gates_count']} validation gates. "
                        f"Awaiting human approval."
                    ),
                    "severity": "INFO",
                }
                events.append(ev)
                self._emit_alert(f"CANDIDATE READY: {c_name}", ev["message"], AlertSeverity.INFO)

        # 2. Check for Validation Failures or Probation Entries
        for s in self.portfolio_manager._strategies.values():
            if s.lifecycle_state == StrategyLifecycleState.PROBATION:
                ev = {
                    "type": "STRATEGY_ENTERED_PROBATION",
                    "strategy_name": s.name,
                    "message": f"Live strategy {s.name} entered PROBATION due to performance degradation / elevated drawdown.",
                    "severity": "WARNING",
                }
                events.append(ev)
                self._emit_alert(f"STRATEGY PROBATION: {s.name}", ev["message"], AlertSeverity.WARNING)

            elif s.validation_status == "FAILED":
                ev = {
                    "type": "STRATEGY_VALIDATION_FAILED",
                    "strategy_name": s.name,
                    "message": f"Strategy candidate {s.name} failed validation gates (Max DD > 12.0% in Monte Carlo stress test).",
                    "severity": "WARNING",
                }
                events.append(ev)
                self._emit_alert(f"VALIDATION FAILED: {s.name}", ev["message"], AlertSeverity.WARNING)

        return events

    def _emit_alert(self, title: str, message: str, severity: AlertSeverity) -> None:
        """Emits structured alert and logs to untrusted external memory."""
        try:
            self.alert_manager.create_alert(
                title=title,
                message=message,
                severity=severity,
                category="strategy_evolution",
            )
        except Exception as e:
            logger.debug(f"[EVOLUTION_OVERSIGHT] Alert dispatch failed: {e}")

        if self.memory:
            try:
                msg = Message(
                    role=Role.SYSTEM,
                    content=f"EVOLUTION_ALERT [{severity.value}] {title}: {message}",
                    trust_level=TrustLevel.UNTRUSTED_EXTERNAL,
                )
                self.memory.add_message(msg)
            except Exception as e:
                logger.debug(f"[EVOLUTION_OVERSIGHT] Memory persist failed: {e}")
