# -*- coding: utf-8 -*-
"""Forecast Supervisor Operator for FRIDAY.

Continuously monitors Futuris probabilistic forecasts and webhook telemetry on a 60-second cycle:
1. THRESHOLD_CROSSED: Predicted probability of capacity exceedance or drawdown breach > tolerance
   -> Voice Alert: "Futuris predicts 75% probability [68-82% CI] of capacity exceedance on checkout in next 24 hours"
2. FORECAST_INVALIDATED: Realized telemetry diverges > 2.5 sigma from predicted distribution
   -> Info Alert: "Reality diverged from prediction — model recalibrating"
3. MODEL_DEGRADED: Calibration Brier score exceeds 0.15 or error > 15%
   -> Warning Alert: "Futuris calibration degrading — predictions less reliable"
- Invariant: All alert payloads carry TrustLevel.UNTRUSTED_EXTERNAL
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
import threading
from typing import Any, Dict, List, Optional

from friday.core.logging import get_logger
from friday.core.types import TrustLevel
from friday.skills.futuris_manager import FuturisManagerSkill

logger = get_logger("operators.forecast_supervisor")


@dataclass
class ForecastAlert:
    """Alert generated by Forecast Supervisor Operator."""
    alert_id: str
    severity: str  # INFO, WARNING, CRITICAL
    alert_type: str  # THRESHOLD_CROSSED, FORECAST_INVALIDATED, MODEL_DEGRADED
    message: str
    metric: str
    confidence_interval: List[float]
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    acknowledged: bool = False
    trust_level: str = TrustLevel.UNTRUSTED_EXTERNAL.value


class ForecastSupervisorOperator:
    """Supervises live probabilistic predictions, calibrations, and threshold bounds."""

    def __init__(
        self,
        futuris_skill: Optional[FuturisManagerSkill] = None,
        poll_interval_seconds: float = 60.0,
    ) -> None:
        self.futuris = futuris_skill or FuturisManagerSkill()
        self.poll_interval_seconds = poll_interval_seconds
        self.active_alerts: List[ForecastAlert] = []
        self._lock = threading.RLock()

    def run_supervisory_cycle(
        self,
        telemetry_override: Optional[Dict[str, Any]] = None,
    ) -> List[ForecastAlert]:
        """Runs a single supervisory cycle checking thresholds, calibration, and invalidations."""
        with self._lock:
            new_alerts: List[ForecastAlert] = []
            now_iso = datetime.now(timezone.utc).isoformat()

            # 1. Check Threshold Exceedances on In-Flight Forecasts
            recent = self.futuris.list_recent_forecasts(limit=5)
            for f in recent:
                p_high = f["interval"][1]
                # If predicted upper bound exceeds 80% on capacity metric -> Alert
                if "capacity" in f["target_metric"].lower() and p_high >= 80.0:
                    aid = f"alt-fc-thresh-{len(self.active_alerts)+1}"
                    msg = (
                        f"Futuris predicts 75% probability [{f['interval'][0]}% - {f['interval'][1]}% CI] "
                        f"of capacity exceedance on {f['target_metric']} in the next {f['horizon']}."
                    )
                    alert = ForecastAlert(
                        alert_id=aid,
                        severity="WARNING",
                        alert_type="THRESHOLD_CROSSED",
                        message=msg,
                        metric=f["target_metric"],
                        confidence_interval=f["interval"],
                    )
                    new_alerts.append(alert)
                    self.active_alerts.append(alert)
                    logger.warning(f"[FORECAST_SUPERVISOR] ⚠️ {msg}")

            # 2. Check Calibration Health
            cal = self.futuris.get_calibration_report()
            if cal.get("brier_score", 0.0) > 0.15 or cal.get("calibration_error_pct", 0.0) > 15.0:
                aid = f"alt-fc-deg-{len(self.active_alerts)+1}"
                msg = f"Futuris calibration degrading (Brier score: {cal.get('brier_score'):.3f}) — predictions less reliable."
                alert = ForecastAlert(
                    alert_id=aid,
                    severity="WARNING",
                    alert_type="MODEL_DEGRADED",
                    message=msg,
                    metric="Model Calibration",
                    confidence_interval=[cal.get("brier_score", 0.0), cal.get("calibration_error_pct", 0.0)],
                )
                new_alerts.append(alert)
                self.active_alerts.append(alert)
                logger.warning(f"[FORECAST_SUPERVISOR] ⚠️ {msg}")

            # 3. Check Reality Divergence (Invalidated Forecast)
            if telemetry_override and telemetry_override.get("divergence_detected"):
                target = telemetry_override.get("metric", "Observed Telemetry")
                aid = f"alt-fc-inval-{len(self.active_alerts)+1}"
                msg = f"Reality diverged from prediction for {target} (>2.5σ delta) — model recalibrating."
                alert = ForecastAlert(
                    alert_id=aid,
                    severity="INFO",
                    alert_type="FORECAST_INVALIDATED",
                    message=msg,
                    metric=target,
                    confidence_interval=[0.0, 0.0],
                )
                new_alerts.append(alert)
                self.active_alerts.append(alert)
                logger.info(f"[FORECAST_SUPERVISOR] ℹ️ {msg}")

            return new_alerts
