"""Strategy Portfolio Manager for FRIDAY Evolution Oversight.

Manages strategy lifecycle states (LIVE, INCUBATION, TESTNET, EVOLVING, PROBATION, RETIRED),
tracks strategy age, performance rankings, and candidate evaluation metrics.
"""

import threading
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from friday.core.logging import get_logger

logger = get_logger("trading.strategy_portfolio")


class StrategyLifecycleState(str, Enum):
    """Lifecycle states of quantitative trading strategies."""
    EVOLVING = "EVOLVING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    INCUBATION = "INCUBATION"
    TESTNET = "TESTNET"
    LIVE = "LIVE"
    PROBATION = "PROBATION"
    RETIRED = "RETIRED"
    REJECTED = "REJECTED"


@dataclass
class StrategyCandidate:
    """Strategy candidate generated by the evolution lab."""
    candidate_id: str
    name: str
    description: str
    timeframe: str
    indicators: list[str]
    edge_hypothesis: str
    profit_factor_2y: float
    sharpe_2y: float
    win_rate_pct: float
    max_drawdown_pct: float
    passed_gates_count: int  # e.g., 6 of 6
    validation_status: str  # PASSED, FAILED, IN_PROGRESS
    ai_debate_summary: str
    worst_case_scenario: str
    lifecycle_state: StrategyLifecycleState = StrategyLifecycleState.READY_FOR_REVIEW
    allocated_capital_usdt: float = 0.0
    age_days: int = 0
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class StrategyPortfolioManager:
    """Tracks and organizes all active, candidate, and historical trading strategies."""

    def __init__(self) -> None:
        self._strategies: dict[str, StrategyCandidate] = {}
        self._lock = threading.RLock()
        self._init_defaults()

    def _init_defaults(self) -> None:
        """Initializes default active portfolio strategies and latest candidate."""
        # 1. Active Live Strategies
        self._strategies["BTC_Supertrend_Momentum"] = StrategyCandidate(
            candidate_id="strat_live_01",
            name="BTC_Supertrend_Momentum",
            description="Dynamic trend-following momentum strategy using multi-timeframe ATR Supertrend brackets.",
            timeframe="1h",
            indicators=["ATR_Supertrend", "EMA_200", "Volume_Profile"],
            edge_hypothesis="Captures institutional breakout trends with trailing stop-loss protection.",
            profit_factor_2y=1.92,
            sharpe_2y=2.45,
            win_rate_pct=68.5,
            max_drawdown_pct=2.45,
            passed_gates_count=6,
            validation_status="PASSED",
            ai_debate_summary="Strong consensus (Bull: 9/10, Risk Officer: 8.5/10). Highly robust in high-volatility expansions.",
            worst_case_scenario="Extended choppy sideways ranges generate small consecutive stop-out scratches.",
            lifecycle_state=StrategyLifecycleState.LIVE,
            allocated_capital_usdt=11250.0,
            age_days=180,
        )

        self._strategies["Volatility_Breakout"] = StrategyCandidate(
            candidate_id="strat_live_02",
            name="Volatility_Breakout",
            description="Bollinger Band width expansion breakout strategy on major liquid pairs.",
            timeframe="15m",
            indicators=["Bollinger_Bands", "Keltner_Channels", "ADX"],
            edge_hypothesis="Enters on volatility compression squeezes preceding sharp directional expansion.",
            profit_factor_2y=1.75,
            sharpe_2y=2.05,
            win_rate_pct=61.0,
            max_drawdown_pct=3.10,
            passed_gates_count=6,
            validation_status="PASSED",
            ai_debate_summary="Approved with high conviction (Consensus: 8.2/10). High reward-to-risk ratio.",
            worst_case_scenario="False breakout whipsaws during low-volume holiday regimes.",
            lifecycle_state=StrategyLifecycleState.LIVE,
            allocated_capital_usdt=6250.0,
            age_days=90,
        )

        self._strategies["ETH_Mean_Reversion"] = StrategyCandidate(
            candidate_id="strat_live_03",
            name="ETH_Mean_Reversion",
            description="Statistical mean-reversion strategy trading RSI/Z-score price deviations.",
            timeframe="4h",
            indicators=["RSI_14", "Z_Score", "VWAP"],
            edge_hypothesis="Exploits overextended market sentiment returning to liquidity equilibrium.",
            profit_factor_2y=1.62,
            sharpe_2y=1.75,
            win_rate_pct=57.0,
            max_drawdown_pct=3.85,
            passed_gates_count=6,
            validation_status="PASSED",
            ai_debate_summary="Balanced support (Consensus: 7.8/10). Reliable in ranging sideways regimes.",
            worst_case_scenario="Sustained parabolic trending moves trigger delayed mean reversion.",
            lifecycle_state=StrategyLifecycleState.LIVE,
            allocated_capital_usdt=7500.0,
            age_days=120,
        )

        # 2. Incubation & Candidate Strategies
        self._strategies["Adaptive_Funding_Arb"] = StrategyCandidate(
            candidate_id="strat_inc_04",
            name="Adaptive_Funding_Arb",
            description="Cross-exchange delta-neutral funding rate arbitrage harvester.",
            timeframe="8h",
            indicators=["Funding_Rate_Spread", "Spot_Perp_Basis"],
            edge_hypothesis="Captures positive funding rate yields while hedging spot against perpetual contracts.",
            profit_factor_2y=2.30,
            sharpe_2y=2.60,
            win_rate_pct=88.0,
            max_drawdown_pct=0.85,
            passed_gates_count=6,
            validation_status="PASSED",
            ai_debate_summary="Unanimous approval (Consensus: 9.4/10). Minimal directional market risk.",
            worst_case_scenario="Exchange withdrawal suspension or liquidity squeeze on funding payment epoch.",
            lifecycle_state=StrategyLifecycleState.INCUBATION,
            allocated_capital_usdt=1000.0,
            age_days=14,
        )

        self._strategies["Order_Flow_Imbalance"] = StrategyCandidate(
            candidate_id="strat_cand_05",
            name="Order_Flow_Imbalance",
            description="Microstructure strategy trading cumulative volume delta (CVD) and order book skew.",
            timeframe="5m",
            indicators=["CVD", "Bid_Ask_Imbalance", "Tape_Speed"],
            edge_hypothesis="Capitalizes on aggressive market order absorption at key liquidity levels.",
            profit_factor_2y=1.68,
            sharpe_2y=2.15,
            win_rate_pct=64.2,
            max_drawdown_pct=2.10,
            passed_gates_count=6,
            validation_status="PASSED",
            ai_debate_summary="AI-Universe consensus: 8.7/10. Bull agent highlights high Sharpe in liquid sessions; Risk Officer notes slippage sensitivity.",
            worst_case_scenario="Exchange API latency degradation during extreme news volatility increases slippage.",
            lifecycle_state=StrategyLifecycleState.READY_FOR_REVIEW,
            allocated_capital_usdt=0.0,
            age_days=2,
        )

    def get_candidate(self, name_or_id: str) -> StrategyCandidate | None:
        """Retrieves a strategy by name or candidate ID."""
        with self._lock:
            for s in self._strategies.values():
                if name_or_id.lower() in (s.name.lower(), s.candidate_id.lower()):
                    return s
            return None

    def get_latest_candidate(self) -> StrategyCandidate | None:
        """Returns the primary strategy awaiting human review."""
        with self._lock:
            for s in self._strategies.values():
                if s.lifecycle_state == StrategyLifecycleState.READY_FOR_REVIEW:
                    return s
            return list(self._strategies.values())[-1]

    def update_lifecycle_state(self, name: str, new_state: StrategyLifecycleState) -> bool:
        """Transitions a strategy to a new lifecycle state."""
        with self._lock:
            s = self.get_candidate(name)
            if not s:
                return False
            old_state = s.lifecycle_state
            s.lifecycle_state = new_state
            logger.info(f"[STRATEGY_PORTFOLIO] {s.name} transitioned: {old_state.value} -> {new_state.value}")
            return True

    def get_portfolio_overview(self) -> dict[str, Any]:
        """Returns strategy distribution across all lifecycle stages."""
        with self._lock:
            live = [s for s in self._strategies.values() if s.lifecycle_state == StrategyLifecycleState.LIVE]
            inc = [s for s in self._strategies.values() if s.lifecycle_state == StrategyLifecycleState.INCUBATION]
            cand = [s for s in self._strategies.values() if s.lifecycle_state == StrategyLifecycleState.READY_FOR_REVIEW]
            prob = [s for s in self._strategies.values() if s.lifecycle_state == StrategyLifecycleState.PROBATION]
            ret = [s for s in self._strategies.values() if s.lifecycle_state == StrategyLifecycleState.RETIRED]

            # Sort live by Sharpe ratio
            live_ranked = sorted(live, key=lambda x: x.sharpe_2y, reverse=True)

            return {
                "total_strategies_count": len(self._strategies),
                "live_count": len(live),
                "incubation_count": len(inc),
                "candidate_count": len(cand),
                "probation_count": len(prob),
                "retired_count": len(ret),
                "live_strategies_ranked": [s.__dict__ for s in live_ranked],
                "incubation_strategies": [s.__dict__ for s in inc],
                "candidates_awaiting_review": [s.__dict__ for s in cand],
            }

    def get_spoken_portfolio_summary(self) -> str:
        """Returns concise spoken overview of the strategy portfolio."""
        overview = self.get_portfolio_overview()
        top_strat = overview["live_strategies_ranked"][0] if overview["live_strategies_ranked"] else None

        top_msg = f"Top performing strategy is {top_strat['name']} with a 2-year Sharpe ratio of {top_strat['sharpe_2y']:.2f}." if top_strat else ""

        return (
            f"Strategy portfolio overview: You currently have {overview['live_count']} live strategies deployed across capital, "
            f"{overview['incubation_count']} in incubation, and {overview['candidate_count']} candidate awaiting human approval review. "
            f"{top_msg} All live strategies maintain positive track records."
        )
