"""Cryptographic, single-use, time-bounded Tool Authorization Capability system.

Replaces weak boolean flags (e.g. `allow_sensitive=True`) with unforgeable,
cryptographically signed capability tokens bound to the specific tool name,
arguments hash, safety level, tool call ID, and expiration timestamp.
"""

import hashlib
import hmac
import json
import secrets
import threading
import time
import uuid
from typing import Any

from pydantic import BaseModel, Field

from friday.core.types import SafetyLevel


def compute_arguments_hash(arguments: dict[str, Any]) -> str:
    """Compute a deterministic SHA-256 hash of canonicalized JSON arguments."""
    try:
        canonical_json = json.dumps(arguments or {}, sort_keys=True, separators=(",", ":"), default=str)
    except Exception:
        canonical_json = str(sorted(arguments.items())) if arguments else "{}"
    return hashlib.sha256(canonical_json.encode("utf-8")).hexdigest()


class ToolAuthorizationCapability(BaseModel):
    """Cryptographic authorization token granting single-use execution rights for a specific tool call."""

    capability_id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique capability identifier")
    tool_name: str = Field(..., description="Target tool authorized for execution")
    tool_call_id: str = Field(default="", description="Associated LLM tool call ID")
    args_hash: str = Field(..., description="Deterministic SHA-256 hash of authorized arguments")
    safety_level: SafetyLevel = Field(..., description="Authorized safety classification level")
    purpose: str | None = Field(default=None, description="Declared purpose of tool execution")
    affected_resource: str | None = Field(default=None, description="Resource identifier authorized (e.g. path)")
    created_at: float = Field(default_factory=time.time, description="Epoch timestamp of issuance")
    expires_at: float = Field(..., description="Epoch timestamp after which capability is invalid")
    is_used: bool = Field(default=False, description="Flag indicating if capability was already consumed")
    signature: str = Field(..., description="HMAC-SHA256 signature generated by ToolAuthorizer")

    def is_expired(self) -> bool:
        """Check if capability validity period has elapsed."""
        return time.time() > self.expires_at


class ToolAuthorizer:
    """Authority responsible for issuing and verifying cryptographic ToolAuthorizationCapabilities."""

    def __init__(self, signing_key: bytes | None = None, default_ttl_seconds: float = 60.0) -> None:
        self._signing_key: bytes = signing_key or secrets.token_bytes(32)
        self.default_ttl_seconds: float = default_ttl_seconds
        self._consumed_capability_ids: set[str] = set()
        self._lock: threading.Lock = threading.Lock()

    def _generate_signature(
        self,
        capability_id: str,
        tool_name: str,
        tool_call_id: str,
        args_hash: str,
        safety_level: str,
        expires_at: float,
    ) -> str:
        """Compute HMAC-SHA256 signature for capability attributes."""
        payload = f"{capability_id}:{tool_name}:{tool_call_id}:{args_hash}:{safety_level}:{expires_at:.4f}".encode()
        return hmac.new(self._signing_key, payload, hashlib.sha256).hexdigest()

    def issue_capability(
        self,
        tool_name: str,
        arguments: dict[str, Any],
        safety_level: SafetyLevel,
        tool_call_id: str = "",
        purpose: str = "",
        affected_resource: str = "",
        ttl_seconds: float | None = None,
    ) -> ToolAuthorizationCapability:
        """Issue a new signed, single-use authorization capability for an approved execution request."""
        ttl = ttl_seconds if ttl_seconds is not None else self.default_ttl_seconds
        capability_id = str(uuid.uuid4())
        created_at = time.time()
        expires_at = created_at + max(0.001, ttl)
        args_hash = compute_arguments_hash(arguments)

        sig = self._generate_signature(
            capability_id=capability_id,
            tool_name=tool_name,
            tool_call_id=tool_call_id,
            args_hash=args_hash,
            safety_level=safety_level.value,
            expires_at=expires_at,
        )

        return ToolAuthorizationCapability(
            capability_id=capability_id,
            tool_name=tool_name,
            tool_call_id=tool_call_id,
            args_hash=args_hash,
            safety_level=safety_level,
            purpose=purpose,
            affected_resource=affected_resource,
            created_at=created_at,
            expires_at=expires_at,
            is_used=False,
            signature=sig,
        )

    def verify_and_consume(
        self,
        capability: Any,
        tool_name: str,
        arguments: dict[str, Any],
        tool_call_id: str = "",
    ) -> tuple[bool, str]:
        """Verify the validity of an authorization capability and consume it atomically.

        Returns:
            Tuple of (is_valid, failure_reason_or_ok)
        """
        # 1. Type validation
        if not capability or not isinstance(capability, ToolAuthorizationCapability):
            return False, "Missing or invalid authorization capability object (boolean flags are disallowed)"

        # 2. Expiration check
        if capability.is_expired():
            return (
                False,
                f"Authorization capability expired at {capability.expires_at:.2f} (current: {time.time():.2f})",
            )

        # 3. Tool name match
        if capability.tool_name != tool_name:
            return (
                False,
                f"Authorization capability tool mismatch: authorized for '{capability.tool_name}', but '{tool_name}' was requested",
            )

        # 4. Tool call ID match (if bound)
        if capability.tool_call_id and tool_call_id and capability.tool_call_id != tool_call_id:
            return (
                False,
                f"Authorization capability tool_call_id mismatch: authorized for '{capability.tool_call_id}', but '{tool_call_id}' was requested",
            )

        # 5. Argument tamper validation
        current_args_hash = compute_arguments_hash(arguments)
        if current_args_hash != capability.args_hash:
            return False, "Arguments have been altered after authorization was granted (argument hash mismatch)"

        # 6. Cryptographic signature check
        expected_sig = self._generate_signature(
            capability_id=capability.capability_id,
            tool_name=capability.tool_name,
            tool_call_id=capability.tool_call_id,
            args_hash=capability.args_hash,
            safety_level=capability.safety_level.value,
            expires_at=capability.expires_at,
        )
        if not hmac.compare_digest(capability.signature, expected_sig):
            return False, "Forged or corrupted authorization capability signature"

        # 7. Atomic consumption / Replay prevention
        with self._lock:
            if capability.capability_id in self._consumed_capability_ids or capability.is_used:
                return False, "Authorization capability has already been consumed (replay attack detected)"

            self._consumed_capability_ids.add(capability.capability_id)
            capability.is_used = True

        return True, "Authorized"

    def check_skill_capabilities(
        self,
        skill_name: str,
        required_capabilities: list,
        environment: str | None = None,
        blocked_capabilities: set[str] | None = None,
        allowed_capabilities: set[str] | None = None,
    ) -> tuple[bool, str]:
        """Verify if a Skill's declared required capabilities are permitted in the current environment."""
        import os

        env = (environment or os.getenv("FRIDAY_ENV", "development")).strip().lower()

        # Parse blocked capabilities from environment variable if not explicitly passed
        env_blocked_str = os.getenv("FRIDAY_BLOCKED_CAPABILITIES", "")
        effective_blocked: set[str] = set(blocked_capabilities or set())
        if env_blocked_str:
            effective_blocked.update(c.strip() for c in env_blocked_str.split(",") if c.strip())

        # Parse permitted capabilities from environment variable if set
        env_permitted_str = os.getenv("FRIDAY_PERMITTED_CAPABILITIES", "")
        effective_allowed: set[str] | None = allowed_capabilities
        if effective_allowed is None and env_permitted_str:
            effective_allowed = set(c.strip() for c in env_permitted_str.split(",") if c.strip())

        # Default environment security policies
        if env in ("sandboxed", "restricted"):
            effective_blocked.update({"destructive_shell", "unrestricted_admin", "kernel_exec"})

        # Check each required capability
        for cap in required_capabilities:
            cap_clean = str(cap).strip().lower()
            if cap_clean in effective_blocked:
                return (
                    False,
                    f"Capability Gating Block: Skill '{skill_name}' requires capability '{cap_clean}', which is blocked in '{env}' environment.",
                )
            if effective_allowed is not None and cap_clean not in effective_allowed:
                return (
                    False,
                    f"Capability Gating Block: Skill '{skill_name}' requires capability '{cap_clean}', which is not in the permitted capabilities list for '{env}' environment.",
                )

        return True, f"All {len(required_capabilities)} required capability(ies) permitted for skill '{skill_name}'."


# Process-level default authorizer singleton
tool_authorizer = ToolAuthorizer()
